language: node_js
jdk:
- openjdk15
node_js:
- lts/*
jobs:
  include:
  - stage: gatsby-frontend
    script:
    - cd minsky-gatsby
    - yarn install
    - yarn build
  - stage: java-backend
    script:
    - "(cd minsky-one && mvn install; export MAVEN_RESULT=$?)"
    - if [ "$MAVEN_RESULT" -ne 0 ]; then exit 1; fi
  - stage: deploy
    script: skip
    before_deploy:
    - export TAGNAME=`git describe --tags --abbrev=0`
    - pwd
    - "/home/travis/build/ExeterBScDTS/ECM3432-2021-minsky/deploy-scripts/before-deploy.sh"
    deploy:
      provider: releases
      api_key:
        secure: n2ix5/pwrQiIUw0qb53kMod5mOo3Xc+jFN1iocSVP71gcYsY8w/LpYK3KO4re6+yq64vdu416rKVwHUW96ap0a22oqF8n9p3CebFRqsEYD865QO1QBRCXjWrVmkz9ZWa59GRxhIFdK26Gn59UKXsP34Ee1JmjK2JSbB7HGrk9rH7GokZd2v8ytkrqRDig7kySCdgknzSIt0f/wN6MCLkEOe4psBSIgEF6EakxSukc1sXVWma/jNUhF6x5F9SE3n5aEQ26Vz7n7LCTLuKNcSbbyjlzihG0PWlS5VzRbdGfpHXdTb4s2OSkBNbBoUtTsVPMfKgMGHfzquzZUcMFwuxCrA+M0884ddHzstA0DT5vU9+AQrGchWTlVnoBmAh4SkXGFg0NPgmrwxyeVLf3nu+6u6DQdAifY7op4HluMvmgjQCXNQf0ZoGzX0I6zLAov1lwbcrWSrB0PSACa259Wec3fn3ZuNos+Keuh3O9yWxPxrTsuVQENDztOxijKiETm7N7wRYd+WTSALQyxJHQG23oM+IJoPxVq/Ljv7vfMM8gTisqwsyZdl37lCoVvsfuMKfa3MlXA/tu533AqlVThqE5zWdn4AWK2L8ucbI89BophXxMX7atPEaQHg2bNdpWGxIqTEVIeKC/hnYEMjyr2K8EvvpsZAfczoWLdUcSKQmb4s=
      file:
      - "/home/travis/install-${TAGNAME}.tar.gz"
      - "/home/travis/minskyOne-${TAGNAME}.zip"
      draft: false
      on:
        repo: ExeterBScDTS/ECM3432-2021-minsky
        tags: true
dd:
  secure: G5qPa0yDgHaJOv84LZrXNpDJg3cQIofJ/rhs5bb6B5O5b4JF/3TnIlbuTVm/9cwczhvCGlIstFMbSzSHy9XeSSc/Q0z+qBZlD2x844HXzMSVKbBgjo8/Cr+xLWfF6gbWGMuIMsBVHG90JQqSX1Jk3Ia2L74oRJB2CHIPGOj9ig3CdFsARHI0sqvWPm7X/DyrWceyARHv0qHNkUOGU+5XWJyhuuiCp3qJTqDwFRt4Hd+iOQs9zLWsM5kaoZre175Mh3ZLZ3XBDF97hj0eOTIJyCKiHq5ni3kOsfK03yZsh7wFvpb9E9g+7F+buZ1TfU6Q0qLmGCskQXP3/AyIdsQJiOg6Lxozhkt15mIXDwG7bi+E0jaZloOzD7D9Pjxrc6iZJCHb0hSR0VFXpBP80+TP9Q/jE+buwT2hrsedkyUWN6SYkX2M5hf2atasvQtVDkRPWxSvWsOwz3iIbGk9hPFRB7xMAUxFYA6BAPPjyBiuLbHvPUsYp7n3Wi14+fYkgt4oPojmuGt1IFLYLb+8CRWaOTcpFrnHS2AUpzDnZQpqpz/5WhZ9Y4cFzsCEB1FaXHgTUTvkfF1cJ2C1FDXcBIdMD59sS0edxOgWPYC1ZGaGEKk8Nd9UmjGNi7WGdbjW7tfRtNNOiSEMEhlDUg/A5nkjfQ1/i86gc6gScC3df0je+aA=
