jobs:
  include:
  - stage: gatsby-frontend
    language: node_js
    node_js:
    - lts/*
    script:
    - cd minsky-gatsby
    - yarn install
    - yarn build
  - stage: java-backend
    language: java
    jdk:
    - openjdk15
    script:
    - "(cd minsky-one && mvn install; export MAVEN_RESULT=$?)"
    - if [ "$MAVEN_RESULT" -ne 0 ]; then exit 1; fi
  - stage: deploy
    script: skip
    before_deploy:
    - export TAGNAME=`git describe --tags --abbrev=0`
    - pwd
    - "/home/travis/build/ExeterBScDTS/ECM3432-2021-minsky/deploy-scripts/before-deploy.sh"
    deploy:
      provider: releases
      api_key:
        secure: "hBV7xCr7pARbKOmPjEtIUzVcjr5EN8wvOcymFc9uaj4kd/F0QSjYeeUdmvfNEBEXwExsZqEBay3whyAzWHfWZmsnMNmMhG1Q1kbHQ5wPCjfyu0UiOm/Y3PmtTG7EGPKEDOqpf5RbizKOnxziJB11IdlARMY9YaPi1AzxO9SdFwuy0s1czz8EYtPcfZIYXIziN47AnN7BSVJGYtzo7gV7cBqoCN9OVeBlBxEui4l1PXroXimQ3d3prLnumzptMQcT4j0X0q/BkuWYVeBZmU3CAn35E7ysc3Ev3IJTJHdnDtWktyhl94EtIqDIbM9fEbi1U8uEayoCgh4JBVNjNFJ3KuZjl0r0W0tCqCMLkfXVcAQmPO5vJWwu2NmbUH572jYUkVYRH7vgmOYpJKlfeE4mrYyIw0QFIMkNbrJhqrzR0rFozEnNn7KE+PGiW19imYRjz+UIQItd831sHazFdxK2N0S9Mp339w8BmT/VBNn9y4MVsJuvPh2lwu65NiQX5I+NxSF1wcKWVrkNaOgujMlfSbgwyyvVGZLaswjylEbIz4hqRNFJn5ubHNms78RqYS6ruVtcyHr/DKss220UkfeafCSnpk1mfr2EOV6xYXuiHgvzoqsOD/kTY4jSKXSAjiuXof7fjy3t0vekPcaxokJotr4Ep8SDlYPlNVJ4EwG9Y0c="
      file:
      - "/home/travis/install-${TAGNAME}.tar.gz"
      - "/home/travis/minskyOne-${TAGNAME}.zip"
      draft: false
      on:
        repo: ExeterBScDTS/ECM3432-2021-minsky
        tags: true
